---
title: "Schedule"
subtitle: "DATA 202: Statistically Measuring and Modeling Social Justice"
---

::: column-screen-inset-right
|  Part   |      Week       | Day           | Topics                                           | HWs                      |          Labs           |            Papers             |                      Other                      |     |
|:------:|:------:|--------|--------|--------|:------:|:------:|:------:|:------:|
|    I    | [1](week1.html) | Tues, Aug 22  | [Introduction to the course](index.html)         | [HW 0](assignments.html) | [Lab 0](computing.html) |                               |                                                 |     |
|         | [2](week2.html) | Tues, Aug 29  | [Foundations](week2-slides.html)                 |                          |                         |     [Paper 1](week1.html)     |                                                 |     |
|         | [3](week3.html) | Tues, Sept 5  | [Theory construction](week3-slides.html)         |                          |                         |        (Paper 1 edits)        |                                                 |     |
|         | [4](week4.html) | Tues, Sept 12 | [More on theory construction](week4-slides.html) |                          |                         |        (Paper 1 edits)        |                                                 |     |
|   II    | [5](week5.html) | Tues, Sept 19 | [Univariate analysis](week5-slides.html)         |                          |                         |        (Paper 1 edits)        |                                                 |     |
|         | [6](week6.html) | Tues, Sept 26 | [Exploratory data analysis](week6-slides.html)   | [HW 1](hw/hw1.html)      | [Lab 1](labs/lab1.html) |                               |                                                 |     |
|         | [7](week7.html) | Tues, Oct 3   | [Bivariate analysis](week7-slides.html)          |                          |                         |                               | [Annotated bibliography](papers/annotated.html) |     |
|         | [8](week8.html) | Tues, Oct 10  | [Notes on causal theories](week8-slides.html)    |                          |                         | [Paper 2](papers/paper2.html) |                                                 |     |
|   III   |        [9](week9.html)        | Tues, Oct 17  | [Modeling social in/justice](week9-slides.html)                       | [HW 2](hw/hw2.html)                     |          [Lab 2](labs/lab2.html)          |                               |                                                 |     |
|         |       10        | Tues, Oct 24  | Bivariate regression analysis                    |                          |                         |                               |               Midterm examination               |     |
|         |       11        | Tues, Oct 31  | Complex theories                                 | HW 3                     |          Lab 3          |                               |                                                 |     |
|         |       12        | Tues, Nov 7   | Multivariate regression (part a)                 |                          |                         |            Paper 3            |                                                 |     |
|   IV    |       13        | Tues, Nov 14  | Multivariate regression (part b)                 | HW 4                     |          Lab 4          |                               |                                                 |     |
|         |       14        | Tues, Nov 21  | Overview of additional models                    |                          |                         |                               |                                                 |     |
|         |       15        | Tues, Nov 28  | Wrap-up                                          | HW 5                     |          Lab 5          |                               |                                                 |     |
| Wrap-up |       16        | Tues, Dec 5   | Open office hours                                |                          |                         |            Paper 4            |                                                 |     |
|         |       17        | Tues, Dec 12  | No class meeting                                 |                          |                         |                               |                Final examination                |     |
:::
