---
title: "Lab 5"
subtitle: "DATA 202 - Alexander - Fall 2023"
format: 
  html:
    self-contained: true
    self-contained-math: true
  pdf: 
    toc: false
    lof: false
    lot: false
    number-sections: false
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    colorlinks: true
pdf-engine: pdflatex
editor: visual
---

For Lab 5, you may submit your solutions to Canvas as a `.pdf` or an *R Script* or even as a `.txt` file.

Please see the *Preparing Lab Reports* at the bottom of the [lab 1](labs/lab1.qmd) assignment.

## Learning Objectives

The `Lab 5` assignment focuses on you exploring multiple variables located in gssr.

Your analyses in this lab should focus on a *complex analysis of multiple variables and their interactions*. Specifically, your path model should indicate the associations between the multiple variables in your model and make use of a complex theoretical relationship to develop your path model and subsequent theories.

**Please note: you may use the same variables from a previous assignment but please use different questions.**

Your analysis in lab 5 may inform the (optional) paper 5 assignment. Ideally, you will use similar constructs to those described in paper 1.
