<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nathan Alexander, PhD">

<title>DATA 202: Statistically Measuring and Modeling Social Justice - DATA 202 - Week 8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./week9.html" rel="next">
<link href="./week7.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="DATA 202: Statistically Measuring and Modeling Social Justice - DATA 202 - Week 8">
<meta property="og:description" content="Notes on causal theories">
<meta property="og:image" content="https://github.com/data-202/img/wk8-a-3.jpg">
<meta property="og:site-name" content="DATA 202: Statistically Measuring and Modeling Social Justice">
<meta name="twitter:title" content="DATA 202: Statistically Measuring and Modeling Social Justice - DATA 202 - Week 8">
<meta name="twitter:description" content="Notes on causal theories">
<meta name="twitter:image" content="https://github.com/data-202/img/wk8-a-3.jpg">
<meta name="twitter:creator" content="@professornaite">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./week1.html">Weekly materials</a></li><li class="breadcrumb-item"><a href="./week8.html">Week 8</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./img/dubois-loc.jpg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://data-202.github.io/fa23" rel="" title="GitHub organization" class="quarto-navigation-tool px-1" aria-label="GitHub organization"><i class="bi bi-github"></i></a>
    <a href="https://canvas.howard.edu/courses/40683" rel="" title="Canvas site" class="quarto-navigation-tool px-1" aria-label="Canvas site"><i class="bi bi-code-square"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course landing page</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./course-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./computing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Weekly materials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Week 8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Appendix</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Homeworks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw/hw1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HW 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw/hw2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HW 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hw/hw3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HW 3</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Labs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/lab1.qmd" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/lab2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 2</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Papers</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./papers/annotated.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./papers/paper2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paper 2</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Solutions</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#review-of-week-7-code" id="toc-review-of-week-7-code" class="nav-link active" data-scroll-target="#review-of-week-7-code">Review of Week 7 code</a></li>
  <li><a href="#part-i-context" id="toc-part-i-context" class="nav-link" data-scroll-target="#part-i-context">Part I: Context</a>
  <ul class="collapse">
  <li><a href="#history-cause-and-effect" id="toc-history-cause-and-effect" class="nav-link" data-scroll-target="#history-cause-and-effect">History, cause, and effect</a></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation">Correlation</a></li>
  <li><a href="#causation" id="toc-causation" class="nav-link" data-scroll-target="#causation">Causation</a></li>
  <li><a href="#associating-x-and-y" id="toc-associating-x-and-y" class="nav-link" data-scroll-target="#associating-x-and-y">Associating X and Y</a></li>
  <li><a href="#framing-spurious-relationships" id="toc-framing-spurious-relationships" class="nav-link" data-scroll-target="#framing-spurious-relationships">Framing spurious relationships</a></li>
  <li><a href="#confounding-variables" id="toc-confounding-variables" class="nav-link" data-scroll-target="#confounding-variables">Confounding variables</a></li>
  <li><a href="#mediating-variables" id="toc-mediating-variables" class="nav-link" data-scroll-target="#mediating-variables">Mediating variables</a></li>
  <li><a href="#moderating-variables" id="toc-moderating-variables" class="nav-link" data-scroll-target="#moderating-variables">Moderating variables</a></li>
  <li><a href="#real-world-associations" id="toc-real-world-associations" class="nav-link" data-scroll-target="#real-world-associations">Real-world associations</a></li>
  </ul></li>
  <li><a href="#part-ii-content" id="toc-part-ii-content" class="nav-link" data-scroll-target="#part-ii-content">Part II: Content</a>
  <ul class="collapse">
  <li><a href="#a-guiding-example" id="toc-a-guiding-example" class="nav-link" data-scroll-target="#a-guiding-example">A guiding example</a></li>
  <li><a href="#a-guiding-example-1" id="toc-a-guiding-example-1" class="nav-link" data-scroll-target="#a-guiding-example-1">A guiding example</a></li>
  <li><a href="#a-closer-look" id="toc-a-closer-look" class="nav-link" data-scroll-target="#a-closer-look">A closer look</a></li>
  <li><a href="#returning-to-the-framework" id="toc-returning-to-the-framework" class="nav-link" data-scroll-target="#returning-to-the-framework">Returning to the framework</a></li>
  </ul></li>
  <li><a href="#part-iii-code" id="toc-part-iii-code" class="nav-link" data-scroll-target="#part-iii-code">Part III: Code</a>
  <ul class="collapse">
  <li><a href="#hypothesis-testing-with-crosstab" id="toc-hypothesis-testing-with-crosstab" class="nav-link" data-scroll-target="#hypothesis-testing-with-crosstab">Hypothesis testing with crosstab</a></li>
  <li><a href="#null-and-alternative-hypothesis-for-a-chi2-test-are" id="toc-null-and-alternative-hypothesis-for-a-chi2-test-are" class="nav-link" data-scroll-target="#null-and-alternative-hypothesis-for-a-chi2-test-are">Null and alternative hypothesis for a <span class="math inline">\(\chi^2\)</span> test are:</a></li>
  <li><a href="#next-up-week-9" id="toc-next-up-week-9" class="nav-link" data-scroll-target="#next-up-week-9"><strong>Next up</strong>: Week 9</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="week8-slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DATA 202 - Week 8</h1>
<p class="subtitle lead">Notes on causal theories</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Nathan Alexander, PhD </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Center for Applied Data Science and Analytics
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<section id="review-of-week-7-code" class="level3">
<h3 class="anchored" data-anchor-id="review-of-week-7-code">Review of <a href="./week7.html#part-iii-code">Week 7 code</a></h3>
</section>
<section id="part-i-context" class="level2">
<h2 class="anchored" data-anchor-id="part-i-context">Part I: Context</h2>
<hr>
<blockquote class="blockquote">
<p>The great masses of people are determined to end the exploitation of their races and land. They are awake and moving toward their goal like a tidal wave. You can hear them rumbling in every village street, on the docks, in the houses, among the students, in the churches, and at political meetings. - Martin Luther King, Jr., <a href="https://www.nobelprize.org/prizes/peace/1964/king/lecture/">Nobel Lecture, December 1964</a></p>
</blockquote>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/wk8-a-3.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Illustration by Yuko Shimizu from <a href="https://www.cigionline.org/articles/as-geopolitical-blocs-vie-for-primacy-in-space-the-history-of-colonization-looms-large/" target="_blank">cigionline.org</a>.</figcaption>
</figure>
</div>
<section id="history-cause-and-effect" class="level3">
<h3 class="anchored" data-anchor-id="history-cause-and-effect">History, cause, and effect</h3>
<p>Theory is often understood through an investigation of both the literature and the historical contexts surrounding a given issue. Take, for example, the legacies of colonization. As data and scientific developments expand into new fields, new questions arise as to what we can associate and how we understand these associations. For example, how does one theoretically relate a series of events from 150 years ago to a present set of conditions? What are the possibilities? What are the limitations? What are the cautionary tales?</p>
<p>Statistics was situated as a vehicle to understand and measure observations. As it becomes an ever popular vehicle to inform social justice discourses, the many real-world associations identified in society bring to mind the well-known and readily available cautionary tale:</p>
<blockquote class="blockquote">
<p>Correlation does not imply causation.</p>
</blockquote>
<p>This popular statement relates to the ability (or inability) to deduce cause-and-effect relationships.</p>
<hr>
</section>
<section id="correlation" class="level3">
<h3 class="anchored" data-anchor-id="correlation">Correlation</h3>
<p>In the traditional setting, correlation is framed as a statistical measure that relays the size and direction of the relationship between two or more variables. From a more critical framework, however, the idea of associations between variables and the attribution of relationships between variables must be both examined and interrogated.</p>
<p>Associations should be understood and initiated from the root of a theoretical framework.</p>
<p>If two variables are related, in a statistical context, we assume that their values <em>change</em> in some ordered fashion. These measures are often represented on an axis depicting the strength of the association.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/wk8-a-2.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Image from statlect.com</figcaption>
</figure>
</div>
<p>As one value of a first variable increases the other variable’s values may also increase (positive relationship). Alternatively, as the value of one variable increases the other variable’s values may decrease (negative relationship). Key questions to consider focus on how context and other factors shape any seeming bivariate relationship.</p>
<hr>
<section id="spurious-correlation" class="level4">
<h4 class="anchored" data-anchor-id="spurious-correlation">Spurious correlation</h4>
<p>At the intersection of mathematics and statistics is the concept of the <a href="https://www.jstor.org/stable/42001453" target="_blank"><em>spurious correlation</em></a> (Ward, 2013). A few examples:</p>
<ul>
<li><p><a href="https://blogs.ams.org/blogonmathblogs/2017/04/10/divorce-and-margarine/" target="_blank">Divorce rate has been found to correlate with margarine use</a>.</p></li>
<li><p>Ice cream sales have been correlated with:</p>
<ul>
<li><p>Swimming deaths</p></li>
<li><p>Shark attacks</p></li>
<li><p>Crime rates</p></li>
</ul></li>
<li><p>The use of the popular site <a href="https://academic.oup.com/jcmc/article/21/4/265/4161784" target="_blank">Facebook has been correlated with diminished well-being</a>.</p></li>
</ul>
<p>These association help us see the need to investigate relationships further. What are possible unexplained relationships in these associations? We identify potential spurious variables when developing theoretical ideas about associations.</p>
<hr>
</section>
</section>
<section id="causation" class="level3">
<h3 class="anchored" data-anchor-id="causation">Causation</h3>
<p>Causality (<a href="https://www.annualreviews.org/doi/full/10.1146/annurev-psych-010814-015135">See Sloman and Acnado (2015)</a>) is a representation and principle of cause and effect. There are many different viewpoints of causation across disciplines and fields of study. Terminology matters in how one frames cause and effect.</p>
<p>There are four possible relationships between two variables:</p>
<ul>
<li><p>X causes Y</p></li>
<li><p>Y causes X</p></li>
<li><p>X and Y are both caused by Z</p></li>
<li><p>X is not related to Y</p></li>
</ul>
<p>While these relationships may exist in some combination, it is important to frame their differences.</p>
<hr>
</section>
<section id="associating-x-and-y" class="level3">
<h3 class="anchored" data-anchor-id="associating-x-and-y">Associating X and Y</h3>
<p>Our initial framing might directly link the variables <code>X</code> and <code>Y</code>.</p>
<p>First, we have the association X causes Y.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  A[X] --&gt; B[Y]
</pre>
</div>
</div>
</div>
</div>
<p>Next, we have the association Y causes X.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  A[Y] --&gt; B[X]
</pre>
</div>
</div>
</div>
</div>
<p>Finally, we have the association X causes Y and Y causes X.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  A[X] &lt;--&gt; B[Y]
  B --&gt; A
</pre>
</div>
</div>
</div>
</div>
<hr>
</section>
<section id="framing-spurious-relationships" class="level3">
<h3 class="anchored" data-anchor-id="framing-spurious-relationships">Framing spurious relationships</h3>
<p>However, after further reading, we may find that we need to integrate a third factor Z.</p>
<p>In this context, a third factor (the “third-cause fallacy”) represents a spurious relationship.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  A[X]
  B[Y]
  C[Z]
</pre>
</div>
</div>
</div>
</div>
<p>Spurious relationships denote an observed or hypothesized association.</p>
<p>There are important differences in how we depict and deal with third factor associations.</p>
<hr>
</section>
<section id="confounding-variables" class="level3">
<h3 class="anchored" data-anchor-id="confounding-variables">Confounding variables</h3>
<p>Confounding is a causal concept that focuses on spurious or distorted associations.</p>
<p>Below, Z is considered a <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4017459/" target="_blank">confounding variable</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph TD
  A[Z] --&gt; B[X]
  A --&gt; C[Y]
</pre>
</div>
</div>
</div>
</div>
<ul>
<li><p>Z is related to both the independent, <span class="math inline">\(X\)</span>, and dependent, <span class="math inline">\(Y\)</span>, variables in the causal sense.</p></li>
<li><p>Your analysis should examine if the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> holds.</p></li>
<li><p>These interactions are described as <em>spurious associations</em>.</p></li>
</ul>
<hr>
</section>
<section id="mediating-variables" class="level3">
<h3 class="anchored" data-anchor-id="mediating-variables">Mediating variables</h3>
<p>A <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4165346/" target="_blank">mediating variable</a> explains the process by which two variables are related.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  A[X] --&gt; B[Z]
  B --&gt; C[Y]
</pre>
</div>
</div>
</div>
</div>
<ul>
<li>Z provides the <em>mechanism</em> to relate the independent, <span class="math inline">\(X\)</span>, and dependent, <span class="math inline">\(Y\)</span>, variables.</li>
</ul>
<hr>
</section>
<section id="moderating-variables" class="level3">
<h3 class="anchored" data-anchor-id="moderating-variables">Moderating variables</h3>
<p>A <a href="https://www.researchgate.net/profile/Hugh-Arnold/publication/240438039_Moderator_Variables_A_Clarification_of_Conceptual_Analytic_and_Psychometric_Issues/links/5ee391fb92851ce9e7dce2ae/Moderator-Variables-A-Clarification-of-Conceptual-Analytic-and-Psychometric-Issues.pdf" target="_blank">moderating variable</a> explains the strength by which two variables are related.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  A[X] --&gt; B[Z]
  A --&gt; C[Y]
  B --&gt; C
</pre>
</div>
</div>
</div>
</div>
<ul>
<li>Z explains the <em>strength of association</em> between the independent, <span class="math inline">\(X\)</span>, and dependent, <span class="math inline">\(Y\)</span>, variables.</li>
</ul>
<hr>
</section>
<section id="real-world-associations" class="level3">
<h3 class="anchored" data-anchor-id="real-world-associations">Real-world associations</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/wk8-a-1.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Image from ACLU.org</figcaption>
</figure>
</div>
<p>Let us look at a more concrete example. Imagine you read or hear the statement:</p>
<blockquote class="blockquote">
<p>“In the U.S., Black drivers are more likely to be pulled over by police than white drivers.”</p>
</blockquote>
<p>This statement represents a complex relationship that requires history and context to inform analysis.</p>
<ul>
<li><p><a href="https://www.aclu.org/issues/racial-justice/race-and-criminal-justice/racial-profiling" target="_blank">Racial profiling</a> has been an issue in the U.S. for centuries.</p></li>
<li><p>U.S. police are <a href="https://www.hrw.org/news/2019/09/12/interview-how-policing-one-us-city-hurts-black-and-poor-communities" target="_blank">deployed at higher rates in some poor and Black neighborhoods</a>.</p></li>
</ul>
<p>What data and evidence do you think is needed to confirm if the statement is accurate? Moreover, what measures and statistical tests would allow us to integrate history and context? What variable associations might be used to assess these relationship?</p>
</section>
</section>
<section id="part-ii-content" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-content">Part II: Content</h2>
<hr>
<section id="a-guiding-example" class="level3">
<h3 class="anchored" data-anchor-id="a-guiding-example">A guiding example</h3>
<p>Let us return to an example mentioned last week: the <a href=""><code>yahoo_data</code></a> in the <code>critstats</code> package. This data comes from a <em>Yahoo! News</em> Race and Justice poll.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/wk7-a-4.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Image from Mass Humanities</figcaption>
</figure>
</div>
<p>A complete description of the data set is as follows:</p>
<blockquote class="blockquote">
<p>Results from a Yahoo! News poll conducted by YouGov on May 29-31, 2020. In total 1060 U.S. adults were asked a series of questions regarding race and justice in the wake of the killing of George Floyd by a police officer. Results in this data set are percentages for the question, “Do you think Blacks and Whites receive equal treatment from the police?” For this particular question there were 1059 respondents.</p>
</blockquote>
<hr>
</section>
<section id="a-guiding-example-1" class="level3">
<h3 class="anchored" data-anchor-id="a-guiding-example-1">A guiding example</h3>
<p>Let us begin with a summary of responses to a survey sparked by the killing of George Floyd.</p>
<table class="table-striped table-hover table">
<caption>Summary of survey response data<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></caption>
<thead>
<tr class="header">
<th style="text-align: center;">Response</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">No</td>
<td style="text-align: center;">700</td>
</tr>
<tr class="even">
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">236</td>
</tr>
</tbody>
</table>
<p>The study sample <span class="math inline">\(n = 936\)</span>. Please take note of the table’s footnote.</p>
<p>As of now, we know very little about the survey (i.e., the context has been stripped away).</p>
<section id="an-initial-question" class="level4">
<h4 class="anchored" data-anchor-id="an-initial-question">An initial question</h4>
<p>Is there a difference in the survey responses?</p>
<hr>
</section>
<section id="framing-proportions" class="level4">
<h4 class="anchored" data-anchor-id="framing-proportions">Framing proportions</h4>
<p>As you learn about hypothesis testing, you want to understand the nature of variable associations. There are many approaches to how we measure associations. One we’ll explore extensively is differences in proportions of two dichotomous variables.</p>
<p>First, we add a third column to our table by computing the proportion in each row:</p>
<p><span class="math display">\[ P(No) = \frac{\text{Number of respondents who replied No}}{n} \]</span></p>
<p><span class="math display">\[ P(Yes) = \frac{\text{Number of respondents who replied Yes}}{n} \]</span></p>
<hr>
</section>
<section id="understanding-proportions" class="level4">
<h4 class="anchored" data-anchor-id="understanding-proportions">Understanding proportions</h4>
<table class="table-striped table-hover table">
<caption>Summary of survey response data with proportion column</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Response</th>
<th style="text-align: center;">Total</th>
<th style="text-align: center;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">No</td>
<td style="text-align: center;">700</td>
<td style="text-align: center;"><span class="math inline">\(0.7478\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">236</td>
<td style="text-align: center;"><span class="math inline">\(0.2522\)</span></td>
</tr>
</tbody>
</table>
<p>So we have <span class="math inline">\(P(No) = 0.7478\)</span> and <span class="math inline">\(P(Yes) = 0.2522\)</span>.</p>
<p>This is a sample. Be mindful of the notes about sampling and sampling error.</p>
<p><strong>What can these proportions tell us about the data?</strong></p>
<hr>
</section>
</section>
<section id="a-closer-look" class="level3">
<h3 class="anchored" data-anchor-id="a-closer-look">A closer look</h3>
<p>Let’s look at a preview panel of the full data set.</p>
<table class="table-striped table-hover table">
<caption>Preview of full survey response data set</caption>
<thead>
<tr class="header">
<th style="text-align: center;">ID</th>
<th>Race</th>
<th>Response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td>White</td>
<td>Yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td>White</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">.</td>
<td>.</td>
<td>.</td>
</tr>
<tr class="even">
<td style="text-align: center;">773</td>
<td>Black</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">774</td>
<td>Black</td>
<td>Yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">..</td>
<td>..</td>
<td>..</td>
</tr>
<tr class="odd">
<td style="text-align: center;">874</td>
<td>Hispanic</td>
<td>Yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">875</td>
<td>Hispanic</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(1059\)</span></td>
<td>Other</td>
<td>Not sure</td>
</tr>
</tbody>
</table>
<hr>
<p>When we format the data into tables, there are multiple categories to consider.</p>
<p>In the table below, the <code>race</code> variable is listed in rows.</p>
<div id="tbl-first" class="anchored">
<table class="table">
<caption>Table&nbsp;1: Race in rows</caption>
<thead>
<tr class="header">
<th>Race</th>
<th>No</th>
<th>Yes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Black</td>
<td>Black <span class="math inline">\(\cap\)</span> No</td>
<td>Black <span class="math inline">\(\cap\)</span> Yes</td>
</tr>
<tr class="even">
<td>Hispanic</td>
<td>Hispanic <span class="math inline">\(\cap\)</span> No</td>
<td>Hispanic <span class="math inline">\(\cap\)</span> Yes</td>
</tr>
<tr class="odd">
<td>Other</td>
<td>Other <span class="math inline">\(\cap\)</span> No</td>
<td>Other <span class="math inline">\(\cap\)</span> Yes</td>
</tr>
<tr class="even">
<td>White</td>
<td>White <span class="math inline">\(\cap\)</span> No</td>
<td>White <span class="math inline">\(\cap\)</span> Yes</td>
</tr>
</tbody>
</table>
</div>
<p>Recall that the <span class="math inline">\(\cap\)</span> represents “and” while the <span class="math inline">\(\cup\)</span> represents “or” in logic.</p>
<hr>
<p>In the table below, the <code>response</code> variable is listed in rows.</p>
<div id="tbl-second" class="anchored">
<table class="table">
<caption>Table&nbsp;2: Response in rows</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Response</th>
<th>Black</th>
<th>Hispanic</th>
<th>Other</th>
<th>White</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No</td>
<td>No <span class="math inline">\(\cap\)</span> Black</td>
<td>No <span class="math inline">\(\cap\)</span> Hispanic</td>
<td>No <span class="math inline">\(\cap\)</span> Other</td>
<td>No <span class="math inline">\(\cap\)</span> White</td>
</tr>
<tr class="even">
<td>Yes</td>
<td>Yes <span class="math inline">\(\cap\)</span> Black</td>
<td>Yes <span class="math inline">\(\cap\)</span> Hispanic</td>
<td>Yes <span class="math inline">\(\cap\)</span> Other</td>
<td>Yes <span class="math inline">\(\cap\)</span> White</td>
</tr>
</tbody>
</table>
</div>
<hr>
<p>We use our understanding of probability to generate a reconstruction for the response ‘No’.</p>
<p><span class="math display">\[ P(No) = \dfrac{\text{No} \cap \text{Black}}{n} + \dfrac{\text{No} \cap \text{Hispanic}}{n} + \dfrac{\text{No} \cap \text{Other}}{n} + \dfrac{\text{No} \cap \text{White}}{n} \]</span></p>
<p>We generate a parallel construction for the response ‘Yes’.</p>
<p><span class="math display">\[ P(Yes) = \dfrac{\text{Yes} \cap \text{Black}}{n} + \dfrac{\text{Yes} \cap \text{Hispanic}}{n} + \dfrac{\text{Yes} \cap \text{Other}}{n} + \dfrac{\text{Yes} \cap \text{White}}{n} \]</span></p>
<hr>
<section id="summary-values" class="level4">
<h4 class="anchored" data-anchor-id="summary-values">Summary values</h4>
<p>Adding values to the table will give us a more complete picture of the data.</p>
<table class="table-striped table-hover table">
<caption>Responses to a survey question by race</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Response</th>
<th style="text-align: center;">Black</th>
<th style="text-align: center;">Hispanic</th>
<th style="text-align: center;">Other</th>
<th style="text-align: center;">White</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">No</td>
<td style="text-align: center;">92</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">486</td>
</tr>
<tr class="even">
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">201</td>
</tr>
</tbody>
</table>
<hr>
<p>Use the table to calculate <code>Response</code> probabilities:</p>
<table class="table-striped table-hover table">
<caption>Responses to a survey question by race</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Response</th>
<th style="text-align: center;">Black</th>
<th style="text-align: center;">Hispanic</th>
<th style="text-align: center;">Other</th>
<th style="text-align: center;">White</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">No</td>
<td style="text-align: center;">92</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">486</td>
<td style="text-align: right;">700</td>
</tr>
<tr class="even">
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">201</td>
<td style="text-align: right;">236</td>
</tr>
</tbody>
</table>
<p>Gather response probabilities for <code>No</code> by dividing each cell by the sample size.</p>
<p><span class="math display">\[ P(No) = \dfrac{92}{936} + \dfrac{75}{936} + \dfrac{47}{936} + \dfrac{486}{936} = \dfrac{700}{936} = 0.7478 \]</span> Gather response probabilities for <code>Yes</code> by dividing each cell by the sample size.</p>
<p><span class="math display">\[ P(Yes) = \dfrac{6}{936} + \dfrac{15}{936} + \dfrac{14}{936} + \dfrac{201}{936} = \dfrac{236}{936} = 0.2522 \]</span> We will use this framing to compute proportions for each cell but in R.</p>
<hr>
<p>Given that we want to explore the data in more detail and understand any base associations, we need to revisit our framing and consider some additional tasks.</p>
</section>
</section>
<section id="returning-to-the-framework" class="level3">
<h3 class="anchored" data-anchor-id="returning-to-the-framework">Returning to the framework</h3>
<p>A basic analysis goes a long way in determining our next steps.</p>
<p>With this base analytic exercises, you may want to ask: <em>What is the research question?</em></p>
<p>What are the <strong>main</strong> or <strong>primary</strong> theoretical constructions?</p>
<ul>
<li><p>First, examine the literature and annotate specific citations.</p></li>
<li><p>Next, construct a framework for the various interpretations.</p>
<ul>
<li><p>What are the similarities across theoretical constructions?</p></li>
<li><p>What are the main differences across theoretical constructions?</p></li>
<li><p>How does a nuanced view of the history of the issue improve our understanding?</p></li>
</ul></li>
</ul>
<p>Based on your background analyses, what is the hypothesis?</p>
<hr>
</section>
</section>
<section id="part-iii-code" class="level2">
<h2 class="anchored" data-anchor-id="part-iii-code">Part III: Code</h2>
<hr>
<section id="setting-things-up" class="level4">
<h4 class="anchored" data-anchor-id="setting-things-up">Setting things up</h4>
<p>As a general rule, always load the appropriate libraries at the start of your analyses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load our libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(critstats)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(descr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this case:</p>
<ul>
<li><p><code>critstats</code> contains the <code>yahoo_data</code> that we’d like to analyze.</p></li>
<li><p><code>tidyverse</code> contains the set of functions to help us work with our data</p></li>
<li><p><code>descr</code> and <code>Hmisc</code> contain useful functions to analyze social science data.</p></li>
</ul>
<p>If you receive an error, you may need to use the <code>install.packages()</code> commands first.</p>
<hr>
</section>
<section id="load-the-data" class="level4">
<h4 class="anchored" data-anchor-id="load-the-data">Load the data</h4>
<p>Inspect the data documentation and contents of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># access the yahoo_data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>??yahoo_data</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>yahoo_data <span class="co"># "Do you think Blacks and Whites receive equal treatment from the police?"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>While the specific wording of the question may not fit our theoretical framing (e.g.&nbsp;<code>Blacks</code> and <code>Whites</code>), it is useful to consider what information and insights can be gathered from the data.</p>
<p>Here, theory and the literature become important components to outlining your analytic plan.</p>
<hr>
</section>
<section id="clean-your-data" class="level4">
<h4 class="anchored" data-anchor-id="clean-your-data">Clean your data</h4>
<p>The data in the <code>yahoo_data</code> set is already cleaned and prepped. However, when you conduct your own analyses, you will need to follow the series of steps outlined in previous assignments. For example, <a href="labs/lab1.html">Lab 1</a> is a great resource on cleaning.</p>
<hr>
</section>
<section id="understand-your-data" class="level4">
<h4 class="anchored" data-anchor-id="understand-your-data">Understand your data</h4>
<p>Given that we are analyzing categorical data, we will create a series of tables.</p>
<p>These tables will allow us to gather a sense of the data.</p>
<p>Our first table will be of the variable <code>race_eth</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a table of the race_eth</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(yahoo_data<span class="sc">$</span>race_eth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Black Hispanic    Other    White 
     101      104       82      772 </code></pre>
</div>
</div>
<p>What do you notice? What do you wonder?</p>
<hr>
</section>
<section id="understand-your-data-1" class="level4">
<h4 class="anchored" data-anchor-id="understand-your-data-1">Understand your data</h4>
<p>Our second table will be of the variable <code>response</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a table of the race_eth</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(yahoo_data<span class="sc">$</span>response)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      No Not sure      Yes 
     700      123      236 </code></pre>
</div>
</div>
<p>What do you notice? What do you wonder?</p>
<hr>
</section>
<section id="modify-your-data" class="level4">
<h4 class="anchored" data-anchor-id="modify-your-data">Modify your data</h4>
<p>Make the necessary modifications to your data.</p>
<p>Here I set the <code>yahoo_data</code> to <code>df</code> and rename the <code>race_eth</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> yahoo_data <span class="co"># set the yahoo_data to df</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"race"</span> <span class="ot">=</span> <span class="st">"race_eth"</span>) <span class="co"># rename the race_eth variable to race</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="get-the-sample-size" class="level4">
<h4 class="anchored" data-anchor-id="get-the-sample-size">Get the sample size</h4>
<p>When looking at the table, it may be useful to get a sense of the <em>proportions</em>.</p>
<p>We’ll begin with getting the sample size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get a quick count of the sample size</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(df) <span class="co"># the count function can collect the sample size, n, of a tibble</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1  1059</code></pre>
</div>
</div>
<p>The tables give us the <strong>frequency</strong> of each category.</p>
<p>The sample size will help us get the <strong>relative frequency</strong> of each category.</p>
<hr>
</section>
<section id="relative-frequencies-by-race" class="level4">
<h4 class="anchored" data-anchor-id="relative-frequencies-by-race">Relative frequencies by race</h4>
<p>Get the relative frequencies for the <code>race</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(race) <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">prop.table</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  race         n   prop
  &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
1 Black      101 0.0954
2 Hispanic   104 0.0982
3 Other       82 0.0774
4 White      772 0.729 </code></pre>
</div>
</div>
<hr>
</section>
<section id="relative-frequencies-by-response" class="level4">
<h4 class="anchored" data-anchor-id="relative-frequencies-by-response">Relative frequencies by response</h4>
<p>Get the relative frequencies for the <code>response</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(response) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">prop.table</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  response     n  prop
  &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt;
1 No         700 0.661
2 Not sure   123 0.116
3 Yes        236 0.223</code></pre>
</div>
</div>
<hr>
</section>
<section id="generate-a-crosstab-of-race-and-response" class="level4">
<h4 class="anchored" data-anchor-id="generate-a-crosstab-of-race-and-response">Generate a <code>crosstab</code> of <code>race</code> and <code>response</code></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(df<span class="sc">$</span>response, df<span class="sc">$</span>race, <span class="at">plot=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cell Contents 
|-------------------------|
|                   Count | 
|-------------------------|

=======================================================
               df$race
df$response    Black   Hispanic   Other   White   Total
-------------------------------------------------------
No                92         75      47     486     700
-------------------------------------------------------
Not sure           3         14      21      85     123
-------------------------------------------------------
Yes                6         15      14     201     236
-------------------------------------------------------
Total            101        104      82     772    1059
=======================================================</code></pre>
</div>
</div>
<p>What do you notice? What do you wonder?</p>
<p>Set <code>plot=T</code> if you want to see a visual plot of the data.</p>
<hr>
</section>
<section id="standardize-the-frequencies" class="level4">
<h4 class="anchored" data-anchor-id="standardize-the-frequencies">Standardize the frequencies</h4>
<p>Raw frequencies can be hard to read in a crosstab, especially since column totals are not equal.</p>
<p>Add <code>prop.c = T</code> to get column percentages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(df<span class="sc">$</span>response, df<span class="sc">$</span>race, <span class="at">plot=</span>F, <span class="at">prop.c=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cell Contents 
|-------------------------|
|                   Count | 
|          Column Percent | 
|-------------------------|

=======================================================
               df$race
df$response    Black   Hispanic   Other   White   Total
-------------------------------------------------------
No               92         75      47     486     700 
               91.1%      72.1%   57.3%   63.0%        
-------------------------------------------------------
Not sure          3         14      21      85     123 
                3.0%      13.5%   25.6%   11.0%        
-------------------------------------------------------
Yes               6         15      14     201     236 
                5.9%      14.4%   17.1%   26.0%        
-------------------------------------------------------
Total           101        104      82     772    1059 
                9.5%       9.8%    7.7%   72.9%        
=======================================================</code></pre>
</div>
</div>
<p>We also refer to crosstabs as <em>contingency tables</em>; the percentages provide <em>conditional probabilities</em>.</p>
<p>What do you notice? What do you wonder?</p>
<hr>
</section>
<section id="hypothesis-testing-with-crosstab" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-testing-with-crosstab">Hypothesis testing with crosstab</h3>
<p>Develop (or refine) your research question(s).</p>
<p>Examining the relationship between two variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># research inquiry: is there a relationship between the race and response variables?</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># data: survey results from the Yahoo! News race and justice poll</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># note(s): response contains three levels: Yes, No, and Not sure</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Add your research inquiry/question to your preamble.</p>
<p>Notes help you remember import information for writing code. You can also put them in-line.</p>
<hr>
</section>
<section id="null-and-alternative-hypothesis-for-a-chi2-test-are" class="level3">
<h3 class="anchored" data-anchor-id="null-and-alternative-hypothesis-for-a-chi2-test-are">Null and alternative hypothesis for a <span class="math inline">\(\chi^2\)</span> test are:</h3>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: No relationship. The two variables are statistically independent.</p></li>
<li><p><span class="math inline">\(H_1\)</span>: There is a relationship. The two variables are not statistically independent.</p></li>
</ul>
<p>Notice that <span class="math inline">\(H_1\)</span> does not give us information about the direction or strength of the relationships. To test the null hypothesis, we will calculate the <span class="math inline">\(\chi^2\)</span> statistic:</p>
<p><span class="math display">\[\chi^2 = \sum \dfrac{(O-E)^2}{E}\]</span></p>
<p>Where</p>
<ul>
<li><p><span class="math inline">\(O\)</span> is the observed frequency for each cell</p></li>
<li><p><span class="math inline">\(E\)</span> is the expected frequency for each cell</p>
<ul>
<li>The expected frequency is what we’d expected if there is no relationship (<span class="math inline">\(H_0\)</span> is true)</li>
</ul></li>
</ul>
<hr>
<section id="create-a-crosstab-with-raw-frequencies" class="level4">
<h4 class="anchored" data-anchor-id="create-a-crosstab-with-raw-frequencies">Create a crosstab with raw frequencies</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(df<span class="sc">$</span>response, df<span class="sc">$</span>race, <span class="at">plot=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cell Contents 
|-------------------------|
|                   Count | 
|-------------------------|

=======================================================
               df$race
df$response    Black   Hispanic   Other   White   Total
-------------------------------------------------------
No                92         75      47     486     700
-------------------------------------------------------
Not sure           3         14      21      85     123
-------------------------------------------------------
Yes                6         15      14     201     236
-------------------------------------------------------
Total            101        104      82     772    1059
=======================================================</code></pre>
</div>
</div>
<hr>
</section>
<section id="sampling-error" class="level4">
<h4 class="anchored" data-anchor-id="sampling-error">Sampling error</h4>
<p><em>An important note about sampling error</em></p>
<p>There appears to be a relationship between the variable <code>response</code> and <code>race</code>.</p>
<p>However, the data are from a sample. We do not and should not infer that there is a relationship at the population level, but only for the sample data we are analyzing.</p>
<p>Earlier, we saw the difference in proportions by the column differences for “Yes” and “No”. Since we found that the overall population said “No” to the question of fair treatment, we want to take this into consideration when analyzing our data.</p>
<hr>
</section>
<section id="gather-the-expected-frequencies" class="level4">
<h4 class="anchored" data-anchor-id="gather-the-expected-frequencies">Gather the expected frequencies</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(df<span class="sc">$</span>response, df<span class="sc">$</span>race,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">expected=</span>T, <span class="co">#Add expected frequency to each cell</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cell Contents 
|-------------------------|
|                   Count | 
|         Expected Values | 
|-------------------------|

=======================================================
               df$race
df$response    Black   Hispanic   Other   White   Total
-------------------------------------------------------
No                92         75      47     486     700
                66.8       68.7    54.2   510.3        
-------------------------------------------------------
Not sure           3         14      21      85     123
                11.7       12.1     9.5    89.7        
-------------------------------------------------------
Yes                6         15      14     201     236
                22.5       23.2    18.3   172.0        
-------------------------------------------------------
Total            101        104      82     772    1059
=======================================================</code></pre>
</div>
</div>
<hr>
</section>
<section id="add-the-chi-square-contributions" class="level4">
<h4 class="anchored" data-anchor-id="add-the-chi-square-contributions">Add the chi-square contributions</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(df<span class="sc">$</span>response, df<span class="sc">$</span>race,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">expected=</span>T, <span class="co">#Add expected frequency to each cell</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">prop.chisq =</span> T, <span class="co">#Total contribution of each cell </span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cell Contents 
|-------------------------|
|                   Count | 
|         Expected Values | 
| Chi-square contribution | 
|-------------------------|

=========================================================
               df$race
df$response     Black   Hispanic    Other   White   Total
---------------------------------------------------------
No                 92         75       47     486     700
                 66.8       68.7     54.2   510.3        
                9.542      0.569    0.957   1.156        
---------------------------------------------------------
Not sure            3         14       21      85     123
                 11.7       12.1      9.5    89.7        
                6.498      0.305   13.828   0.243        
---------------------------------------------------------
Yes                 6         15       14     201     236
                 22.5       23.2     18.3   172.0        
               12.107      2.885    1.000   4.874        
---------------------------------------------------------
Total             101        104       82     772    1059
=========================================================</code></pre>
</div>
</div>
<hr>
</section>
<section id="calculate-degrees-of-freedom" class="level4">
<h4 class="anchored" data-anchor-id="calculate-degrees-of-freedom">Calculate degrees of freedom</h4>
<p>We have <span class="math display">\[df_{\chi^2} = (r-1)(c-1)\]</span></p>
<p>where r = number of rows in the table and c = number of columns in the table</p>
<hr>
<p>Chi-square critical values</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/wk8-b-1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Chi-square critical values</figcaption>
</figure>
</div>
<hr>
</section>
<section id="gather-critical-value-of-chi-square" class="level4">
<h4 class="anchored" data-anchor-id="gather-critical-value-of-chi-square">Gather critical value of chi-square</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(.<span class="dv">05</span>, <span class="dv">6</span>, <span class="at">lower.tail=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.59159</code></pre>
</div>
</div>
<hr>
</section>
<section id="get-the-chi-square-statistic-from-r" class="level4">
<h4 class="anchored" data-anchor-id="get-the-chi-square-statistic-from-r">Get the chi-square statistic from R</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="do">## get chi-square statistic</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(df<span class="sc">$</span>response, df<span class="sc">$</span>race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  df$response and df$race
X-squared = 53.964, df = 6, p-value = 7.5e-10</code></pre>
</div>
</div>
<hr>
<p>Our focus should be on interpreting the output values.</p>
<p>In the output, you want to examine the following:</p>
<ul>
<li><p>Confirm <span class="math inline">\(\chi^2\)</span> value and degrees of freedom.</p></li>
<li><p>Notice more precise information about the p-value</p>
<ul>
<li>Use this value to make sense of your research inquiry</li>
</ul></li>
<li><p>Does this p-value make sense <em>statistically</em> and <em>substantively</em>?</p></li>
</ul>
<hr>
</section>
<section id="describe-some-initial-limitations-of-analysis" class="level4">
<h4 class="anchored" data-anchor-id="describe-some-initial-limitations-of-analysis">describe some initial limitations of analysis</h4>
<p>Always close out your analyses with a write up of limitations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">### limitation 1: sampling error</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="do">### limitation 2: category reductions</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="do">### limitation 3: cases dropped</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="do">### limitation 4: chi-square test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
</section>
<section id="next-up-week-9" class="level3">
<h3 class="anchored" data-anchor-id="next-up-week-9"><strong>Next up</strong>: Week 9</h3>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Respondents who selected <strong>‘Not sure’</strong> on the survey were moved from this analysis.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./week7.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Week 7</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./week9.html" class="pagination-link">
        <span class="nav-page-text">Week 9</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2023, Nathan Alexander</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This page was built by Nathan Alexander, PhD in <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>